apiVersion: apps/v1
kind: Deployment
metadata:
  name: koa-deployment
  labels:
    app: koa
spec:
  # Specifies that 3 pods should be running in the deployment
  replicas: 3
  selector:
    matchLabels:
      app: koa
  template:
    metadata:
      labels:
        app: koa
    spec:
      containers:
      - name: koa-server
        image: lnachmias/koa-server:latest
        #Commands the container to produce a log named "date.log"
        #This logfile is stored inside the volume mounted directory /var/log

        ports:
        - containerPort: 3000
          name: http-web-svc
        #Mounts the volumes which are specified on volume-config.yaml
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        persistentVolumeClaim:
          claimName: koa-pv-claim


#Service file
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  ports:
    - name: http-web-svc
      protocol: TCP
      port: 80
      nodePort: 30270
  type: LoadBalancer

