#Service file
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  ports:
    - name: http-web-svc
      protocol: TCP
      port: 80
      nodePort: 30270
  type: LoadBalancer
